-- CREATE TABLE User
-- (
--     Id          BIGINT PRIMARY KEY,
--     email       VARCHAR(255) NOT NULL,
--     password    VARCHAR(255) NOT NULL,
--     phoneNumber VARCHAR(20)  NOT NULL
-- );
--
-- CREATE TABLE Client
-- (
--     cpf    VARCHAR(11) PRIMARY KEY,
--     zipCode    VARCHAR(8) NOT NULL,
--     UserId BIGINT     NOT NULL,
--     FOREIGN KEY (UserId) REFERENCES User (Id)
-- );
--
-- CREATE TABLE Store
-- (
--     cnpj   VARCHAR(14) PRIMARY KEY,
--     logo   VARCHAR(255) NOT NULL,
--     UserId BIGINT       NOT NULL,
--     FOREIGN KEY (UserId) REFERENCES User (Id)
-- );
